spring.application.name=collegeevent
server.port=8081

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.graphite.metrics.export.enabled=true
management.graphite.metrics.export.host=graphite
management.graphite.metrics.export.port=2003
management.graphite.metrics.export.protocol=PLAINTEXT
management.graphite.metrics.export.step=10s


management.metrics.tags.application=collegeevent
